#!/usr/bin/env sh

# Exit this script if any exit with a non-zero state
set -e

# Ensure we are in the project root directory. This still allows the script
# to work even if we call it from a different directory in or out of the
# project.
cd "${0%/*}"

# Source env.sh to ensure that all environment variables are loaded.
. ./env.sh

# Run Composer using the drupal-cli service, container is removed on exit
docker compose run \
  --rm \
  --env CLI_CMD_ALIAS="$0" \
  drupal-cli \
  $@
