#!/usr/bin/env sh
## Script to execute docker-compose commands with the correct environment.
##
## Any parameters passed to this script will be passed through to
## docker-compose, for example running `./docker-compose up -d` will
## result in the `up -d` being passed through to `docker-compose`.

## Exit this script if any exit with a non-zero state
set -e

## Ensure we are in the project root directory. This still allows the script
## to work even if we call it from a different directory in or out of the
## project.
cd "${0%/*}"

## Get the directory name of this directory, use that as the project name.
project_name="${PWD##*/}"

## Export keys and values defined in the `.env` file.
if [ -f ".env" ]; then
  # Source the .env file but ignore comments
  export $(grep -v '^#' .env | xargs)
fi

## We need to run docker-compose from the `docker` sub-directory.
cd "docker"

## Run `docker-compose` with the constructed arguments, and pass through
## any arguments/parameters passed to this script.
docker-compose \
  --project-name "$project_name" \
  $@
