# This is the base docker-compose file which runs across all environments
# it is supplemented by environment specific compose files.

version: "3.8"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: 'Dockerfile'
    volumes: [ ../app:/app:ro ]
    tmpfs: [ /tmp ]
    ports: [ 80:8080 ]
    depends_on: [ php-fpm ]
    networks: [ web ]
    read_only: true
    restart: on-failure

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: "Dockerfile"
    volumes: [ ../app:/app:rw ]
    tmpfs: [ /tmp ]
    networks: [ web, db ]
    read_only: true
    restart: on-failure

  php-cron:
    build:
      context: ./php-cron
      dockerfile: "Dockerfile"
    volumes: [ ../app:/app:rw ]
    tmpfs: [ /tmp ]
    networks: [ web, db ]
    read_only: true
    restart: on-failure

  mariadb:
    image: mariadb
    volumes:
      - ../db:/var/lib/mysql:rw
    tmpfs: [ /tmp, /run/mysqld ]
    networks: [ db ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    read_only: true
    restart: on-failure

networks:
  web:
    driver: bridge
  db:
    driver: bridge
