# This is the base docker-compose file which runs across all environments
# it is supplemented by environment specific compose files.

version: "3.8"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: 'Dockerfile'
    volumes:
      - ../log/nginx:/var/log/nginx:rw
      - ../app:/var/www/app:ro
    tmpfs: [ /tmp ]
    ports: [ 80:80 ]
    depends_on: [ php-fpm ]
    networks: [ web ]
    read_only: true
    restart: on-failure

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: "Dockerfile"
    volumes: [ ../app:/var/www/app:rw ]
    tmpfs: [ /tmp ]
    networks: [ web ]
    read_only: true
    restart: on-failure

  php-cron:
    build:
      context: ./php-cron
      dockerfile: "Dockerfile"
    volumes:
      - ../log/cron:/var/log:rw
      - ../app:/var/www/app:rw
    tmpfs: [ /tmp ]
    networks: [ web ]
    read_only: true
    restart: on-failure

networks:
  web:
    driver: bridge
