# This is the base docker-compose file which runs across all environments
# it is supplemented by environment specific compose files.

version: "3.6"

services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../web:/app/web:ro
    tmpfs: [ /tmp ]
    ports: [ 80:8080 ]
    depends_on: [ php-fpm ]
    networks: [ web ]
    read_only: true
    restart: on-failure

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: "Dockerfile"
    volumes:
      - ../vendor:/app/vendor:ro
      - ../private_files:/app/private_files:rw
      - ../web:/app/web:rw
      - ../composer.json:/app/composer.json:ro
      - ../composer.lock:/app/composer.lock:ro
    tmpfs: [ /tmp ]
    networks: [ web, db ]
    read_only: true
    restart: on-failure

  php-cron:
    build:
      context: ./php-cron
      dockerfile: "Dockerfile"
    volumes:
      - ../vendor:/app/vendor:ro
      - ../private_files:/app/private_files:rw
      - ../web:/app/web:rw
      - ../composer.json:/app/composer.json:ro
      - ../composer.lock:/app/composer.lock:ro
    tmpfs: [ /tmp ]
    networks: [ web, db ]
    read_only: true
    restart: on-failure

  mariadb:
    image: mariadb
    volumes:
      - db:/var/lib/mysql:rw
    tmpfs: [ /tmp, /run/mysqld ]
    networks: [ db ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    read_only: true
    restart: on-failure

networks:
  web:
    driver: bridge
  db:
    driver: bridge

volumes:
  db:
