<?php

// phpcs:ignoreFile

/**
 * @file
 *
 * Environment specific settings are stored in this file.
 *
 * This file is copied to web/sites/default/settings.from-env.php by Composer
 * using the Drupal Scaffold plugin.
 *
 * DO NOT EDIT THIS FILE IN web/sites/default/settings.from-env.php ANY CHANGES
 * THERE WILL BE LOST.
 *
 * To edit this file, edit it under assets/drupal-scaffold/settings.from-env.php
 * then run `./cli composer install`, which will copy it to web/sites/default.
 * 
 * This file is included in settings.php.
 */

/**
 * THe name of the environment, for example "dev", "test" or "live".
 */
$env = getenv('ENVIRONMENT');

/**
 * Tell Drupal not to set files in sites/default to read-only, as with few
 * exceptions, we mount most of the file system as read-only inside web server
 * containers, and so this may result in issues if Drupal tries to set
 * permissions but does not have write permission. This can also cause Git to
 * flag these files as changed, which we don't want.
 */
$settings['skip_permissions_hardening'] = TRUE;

/**
 * Set the private files path, we store private files in the /private_files
 * directory at the root of the project, outisde of the web root.
 */
$settings['file_private_path'] = '../private_files';

/**
 * Set the Drupal trusted host patterns, if the DRUPAL_TRUSTED_HOST_PATTERN
 * env variable is set.
 */
if ($trusted_host_pattern = getenv('DRUPAL_TRUSTED_HOST_PATTERN')) {
  $settings['trusted_host_patterns'] = [ $trusted_host_pattern ];
}

/**
 * Settings and config overrides for the dev environment.
 *
 * These settings are copied from the example.settings.local.php file. You
 * can find additional settings in that file which are not set here but may
 * be useful in some cases. The settings here are generally the most useful
 * for development.
 */
if ($env == 'dev') {
  /**
   * Enable local development services.
   */
  $settings['container_yamls'][] = DRUPAL_ROOT . '/sites/development.services.yml';

  /**
   * Show all error messages, with backtrace information.
   */
  $config['system.logging']['error_level'] = 'verbose';

  /**
   * Disable CSS and JS aggregation.
   */
  $config['system.performance']['css']['preprocess'] = FALSE;
  $config['system.performance']['js']['preprocess'] = FALSE;
}
